default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>

test:
  <<: *default
  database: <%= "#{ENV["POSTGRES_DB"]}_test" %>
